.TH ipset-persistent 8
.SH NAME
ipset-persistent \- plugin to load, flush and save ipset rule sets
.SH DESCRIPTION
.B ipset-persistent
adds necessary plugin to netfilter for flush and save ipset rules at boot and halt time.
.fi
You don't need to do anything additional, just use netfilter-persistent to load, flush and save ipset rules.
.SH COPYRIGHT
Copyright (C) 2018 Adrian Ban <adrian@abtelecom.ro>
.PP
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
.SH AUTHORS
Adrian Ban <adrian@abtelecom.ro>
