#!/bin/sh

# This file is part of netfilter-persistent
# Copyright (C) 2018, Adrian Ban <adrian@abtelecom.ro>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.

set -e

rc=0

ipset_cmd="/sbin/ipset"
ipset_dir="/usr/local/sbin /sbin /usr/sbin"

found_ipset=false

for i in $ipset_dir;
do
    if [ -x /$i/ipset ]; then
	found_ipset=true
	ipset_cmd="$i/ipset"
	break
    fi
done

if [ $found_ipset = false ]; then
    echo "INFO: no ipset tools found. Skipping"
    exit 0
fi

load_rules()
{
	#load IPSet rules
	if [ ! -f /etc/ipset/rules ]; then
		echo "Warning: skipping IPSet (no rules to load)"
	else
		$ipset_cmd restore < /etc/ipset/rules 2>&1 | logger -t "$(basename $0)"
		if [ $? -ne 0 ]; then
			rc=1
		fi
	fi
}

save_rules()
{
	#save IPSet rules
	#need at least ip_set loaded:
	/sbin/modprobe -q ip_set 2>&1 | logger -t "$(basename $0)"
	touch /etc/ipset/rules  2>&1 | logger -t "$(basename $0)"
	chmod 0640 /etc/ipset/rules  2>&1 | logger -t "$(basename $0)"
	$ipset_cmd save > /etc/ipset/rules  2>&1 | logger -t "$(basename $0)"
	if [ $? -ne 0 ]; then
		rc=1
	fi
}

case "$1" in
start|restart|reload|force-reload)
	load_rules
	;;
save)
	save_rules
	;;
stop)
	# Why? because if stop is used, the firewall gets flushed for a variable
	# amount of time during package upgrades, leaving the machine vulnerable
	# It's also not always desirable to flush during purge
	echo "Automatic flushing disabled, use \"flush\" instead of \"stop\""
	;;
flush)
	;;
*)
    echo "Usage: $0 {start|restart|reload|force-reload|save|flush}" >&2
    exit 1
    ;;
esac

exit $rc
